FROM nginx:latest

# Install AWS CLI
RUN apt-get update && \
    apt-get install -y awscli

# Copy nginx config file
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
